### ISSUE TITLE
Allow multiple idp's with the same metadatalink

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-auth_saml2#1]
KS laring have requested us to make it so you can have multiple identity providers with the same metadatalink in the auth2_saml plugin.

It's catalyst's plugin and we want to try and merge it into their version. Until then ks will use our fork

**Remember to register time spent!**

**Comment by Anders-Oerbaek-Pedersen** [comment]
Code review by: FMP & SMO
Tested via show and tell with: JRM
