### ISSUE TITLE
Error when using arrow keys in KS login solution.

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-auth_saml2#3]
We have discovered an error in the login solution, where you are sent to the ID portal login if the down arrow key and Enter are used to select municipality affiliation.
Step by step:
1: Go to https://www.kslaring.no/
2: Select "Log in" in the top right corner
3: Enter "Tromsø" in the text box
4: Press the down arrow on the keyboard and then press enter on the keyboard
5: Note that you will then be sent to the login ID port and not Tromsø's SSO.

**Comment by Anders-Oerbaek-Pedersen** [comment]
A bug in `moodle-theme_kslaring`, when listing available identityproviders escapes the URL for HTML rendering, resulting in the URL used when submitting search field with arrows and enter key, results in unavailable parameters in the URL. Things like ampersands are escaped to `&amp;` in the link, mangling the URL parameters.

**Comment by superfoght** [comment]
@Anders-Oerbaek-Pedersen they would discuss this with their own developers. I will re-open if we have to do something..
